### ISSUE TITLE
No thumbnails in downloaded mp3's

### ISSUE THREAD

**Issue by mihannnik** [engatec/vdl#25]
After the download was completed, all music files were left without covers. Is it possible to add the ability to download mp3 with covers? Also, the music does not have authors and titles, which makes it difficult to load such music into the player.
![image](https://user-images.githubusercontent.com/48869235/157775501-b8676fb9-db7b-467d-90a4-203744fe433c.png)
![image](https://user-images.githubusercontent.com/48869235/157775549-7ef887ee-2a39-41cb-9800-1a28d7d1be8b.png)

**Comment by tom54rus** [comment]
Sure. Will add mp3 metadata in the next version.

**Comment by scavchik** [comment]
Sure. Will add mp3 metadata in the next version.

**Comment by scavchik** [comment]
Added metadata and covers support in 1.9. Just check the checkboxes on the settings screen.

![scr](https://user-images.githubusercontent.com/78703355/181376736-ee4d6605-8dba-4309-8398-04b2731356b2.png)

**Comment by mihannnik** [comment]
Thanks for the update. I also wanted to know about adding the ability to download video or audio directly from the page in the browser using the Js function, which seems to be called "Custom URI scheme" and looks like "yourcustomapp://some.parameters". 
On the other hand, I would like to know where the dependencies for self-assembly of this project can be found, since the compiler requires the presence of "com.github.engatec:fx-controls" and I have no idea where I can find this library.

**Comment by scavchik** [comment]
> I also wanted to know about adding the ability to download video or audio directly from the page in the browser using the Js function, which seems to be called "Custom URI scheme" and looks like "yourcustomapp://some.parameters".

Could you elaborate a bit? What's the actual use-case of the feature? If it's just a convenience over copy-paste url then the app can either get urls from the clipboard, or alternatively drag&drop video from the browser.


> On the other hand, I would like to know where the dependencies for self-assembly of this project can be found, since the compiler requires the presence of "com.github.engatec:fx-controls" and I have no idea where I can find this library.

fx-controls is in the `lib` folder (file called `fx-controls-1.0.jar`). You need to install it into your local maven repo first, then you'll be able to build the project. To install it into your maven repo use the following command: `mvn install:install-file -Dfile=fx-controls-1.0.jar -DgroupId=com.github.engatec -DartifactId=fx-controls -Dversion=1.0 -Dpackaging=jar -DgeneratePom=true`
