### ISSUE TITLE
Audio quality settings details

### ISSUE THREAD

**Issue by Fan4Metal** [engatec/vdl#26]
Hi, it would be great to have more details about audio downloads quality. For example bitrate and type of bitrate (VBR/CBR). At present there's only an abstract quality slider.

**Comment by estaf1001** [comment]
oooh. there hasn't been an answer for over a month...

**Comment by scavchik** [comment]
> Hi, it would be great to have more details about audio downloads quality. For example bitrate and type of bitrate (VBR/CBR). At present there's only an abstract quality slider.

Hi. Sure, this actually has been planned for one of the future releases.



> oooh. there hasn't been an answer for over a month...

Sorry, I had other matters to attend and had no time for this project. But I'm back now :)

**Comment by scavchik** [comment]
Added CBR and bitrate support in 1.9. To have bitrate slider visible choose mp3 format and cbr in the dropdown lists on the settings screen.
![scr](https://user-images.githubusercontent.com/78703355/181376231-b07a2a6e-ee38-4ffe-a90c-52d19b3ddecf.png)
