### ISSUE TITLE
What about it could be added a few videos at a time (like a playlist, but only separate videos)?

### ISSUE THREAD

**Issue by mid-ff-play19** [engatec/vdl#28]
Hello everyone!
Not quite a problem, but what about it could be added a few videos at a time (like a playlist, but only separate videos)?
I hope you got what I meant:)

**Comment by scavchik** [comment]
You mean like this? ;)

![image](https://user-images.githubusercontent.com/78703355/182745687-e06564c8-33dc-4afe-9931-83fc5ddf7df0.png)

**Comment by mid-ff-play16** [comment]
> You mean like this? ;)
> 
> ![image](https://user-images.githubusercontent.com/78703355/182745687-e06564c8-33dc-4afe-9931-83fc5ddf7df0.png)

**Comment by mid-ff-play19** [comment]
Yes, BIG thank you for answer!
