### ISSUE TITLE
Cover will be installed in a separate file?

### ISSUE THREAD

**Issue by mid-ff-play19** [engatec/vdl#29]
Hello everyone!
Is it possible in the next updates to add features in which, when downloading video or audio,
the cover will be installed in a separate file?

**Comment by scavchik** [comment]
Just click on a thumbnail (marked with green rectangle on the screenshot) and the program will let you save it as jpg. 

![image](https://user-images.githubusercontent.com/78703355/183156233-7e7a515c-e40d-4c29-9e2d-182eec1a730d.png)

**Comment by mid-ff-play19** [comment]
Oh, thanks. I just didn't guess it to do it)
