### ISSUE TITLE
unwanted ".openjfx" folder creation

### ISSUE THREAD

**Issue by JonnyThree** [engatec/vdl#33]
hello i've found this excellent tool as a gui for yt-dlp, when i use it on windows (portable mode) i see that it creates every time a new folder in my %USERPROFILE% directory named ".openjfx". is this behaviour really necessary? thanks for your attenction

**Comment by scavchik** [comment]
Hi. Thanks for bringing my attention to it. This folder is being created by JavaFX (the gui framework). I'll see what can be done with it and will try to disable this behavior in the following release.

**Comment by JonnyThree** [comment]
> Hi. Thanks for bringing my attention to it. This folder is being created by JavaFX (the gui framework). I'll see what can be done with it and will try to disable this behavior in the following release.

thanks so much for your answer

**Comment by candrapersada** [comment]
> hello i've found this excellent tool as a gui for yt-dlp, when i use it on windows (portable mode) i see that it creates every time a new folder in my %USERPROFILE% directory named ".openjfx". is this behaviour really necessary? thanks for your attenction

add `java-options=-Djavafx.cachedir=$APPDIR\cache` on `vdl.cfg` to create .openjfx in the portable folder

**Comment by JonnyThree** [comment]
> add `java-options=-Djavafx.cachedir=$APPDIR\cache` on `vdl.cfg` to create .openjfx in the portable folder

thanks a lot, it works, however, do you know if there is an option for java to disable this folder creaction?  seems to be something related of some caching activity, it's really necessary?
