### ISSUE TITLE
[Bug] VK video playlist is dislayed incorrectly

### ISSUE THREAD

**Issue by iG8R** [engatec/vdl#35]
Hi.
Windows 10 (21H1, 19043.1415)

While trying downloading playlist from VK video, e.g. https://vk.com/video/playlist/-24440848_54694294 , VDL shows the following result:
![VDL(yt-dlp)-VK-playlist-2023-01-01_212121](https://user-images.githubusercontent.com/11407417/210182539-66aba5cc-f15e-45c4-a51b-3a3535d231a6.jpg)

**Comment by scavchik** [comment]
VDL relies on yt-dlp or youtube-dl to download videos and their data. Simply put it's a GUI for those amazing tools. If they couldn't extract screenshots or some other video details, there's just nothing VDL can do about it :(
