### ISSUE TITLE
[Request] User's arguments

### ISSUE THREAD

**Issue by iG8R** [engatec/vdl#37]
Is there any way to let the user add their arguments for downloads, e.g. `--no-mtime`, `--abort-on-unavailable-fragment` etc.?

**Comment by scavchik** [comment]
Sorry for late response. Yes, user can pass their arguments. There's a checkbox in the preferences `Use configuration file` where all the settings can be customized.
![изображение](https://github.com/engatec/vdl/assets/78703355/1fb0987d-5b4f-4019-ab18-afa99e407fd3)
