### ISSUE TITLE
[bug] YouTube Throttling

### ISSUE THREAD

**Issue by Argimko** [engatec/vdl#38]
Some YT videos throttled (very slow downloading) so we need to put **phantomjs.exe** into the **app** folder to fix it.
Example throttled video: https://www.youtube.com/watch?v=kbVxz5PeI8c

You can see the next output if run: 

`yt-dlp.exe -f - https://www.youtube.com/watch?v=kbVxz5PeI8c`

![image](https://github.com/engatec/vdl/assets/3511036/97bf1108-f365-40bb-abe6-38e834fdcff4)

**Comment by scavchik** [comment]
Doesn't seem like an issue anymore.

**Comment by Argimko** [comment]
Yes, confirm
